language: shell

services:
- docker

jobs:
  include:
  - stage: Build
    name: Build
    if: type = pull_request
    script:
    - make check MUST_GATHER_IMAGE=kubevirt/must-gather
    - make docker-build MUST_GATHER_IMAGE=kubevirt/must-gather
  - stage: Push
    name: Push
    if: type = push
    script:
    - echo $QUAY_PASSWORD | docker login -u $QUAY_USERNAME --password-stdin quay.io
    - make build MUST_GATHER_IMAGE=kubevirt/must-gather

env:
  global:
  # QUAY_USERNAME
  - secure: "CQ/ki3/+XY79JHXAMN7QKute3o94E04LEiPYo0im3kQF71+2YfaTk4hFN+EM5ZvHzL9QRmNPyrRY2TfgP30eweJNOGpD7P1ea5GHnHxzdcNDcvsgS8KwH/DeLkYdsXkUHY4juODLDVV6VAaIP5teL8r6Kce4hFOvOPzTu8O25rWcANWHX7zVQn4srjWUbdHjKF91T48ojyj9SLTDQvaiksRN2eu495+65Mb1pKYUP23znDQFNJpoz08ClZn2SzjoI19WFUTlEr69AvH/jo3VTZ7PJWIM7mwdl7h7/5y2RDcdU5F7rl5y2uf1neTpVD9mMRhBG4cYNLwOVSQDZoCKhdc/Jl5PPem7dhpHcEV799/3aCOm72ViNuDIv/4FG3wr2kJ/UacwruBwKijip9iKTGKjBq6lhzLC1MOx3eKLN76N7wImmoZdS2/SSDlPvahfFFDfkqIhVj0tWiTCY5p8RfjzPH+8c6MaglgKyTJKP7fdvvad0A5mRtSFDBb9d5FPtLgybAQyrngj4fIGhHZbvWIhikTfol2dgFqbHSxfnMXVi4piOjna8+s7SdtuQzluCvdfDEZsRVbjJ30/bC4z227+6gTW9dRt1zcdGnurP6/kBqysdkczk+H/JiOTJC0uCBHRrksrkIyFNd5eMbKBZkiJydnviYZGw33doWjHjgc="
  # QUAY_PASSWORD
  - secure: "BDkmwezPFP7v1S50ZQs+bNrdA2dLpq780FrQ8XzF6xG0MJhxCH3BJcVwkij6q8ZrrparM9zSJyD7McvocVdYoLGeDRJtn3m3JE1aNAnv23tD6Kww01TfZ9oyIb+9O4FG0DonXVLgcGNfnWnxEGB4oo0Fd5YyahOtMVOshPZXoFtupuX5m8LcUPzvck87sf8RRqCmzismBzPfih0oFz1zrudYl/pbHqn3DD0bvVbZzqwh6yCSSLauKmKBQmeRLrFi7I9T+zwoToNAVxvC8o2cn49Q7ZYo6A7/e0jxryCgqkrN1q5ZMm4g2mmeOT7cpSjXe8FH4fc3KqIsUvZe4/G92L0qVHwpnbMEWmTFc/aMMYvM/tpNI46zZoCfRgLWxkyoTMthhY04fpf4202wAYA51uQ/OMqAZqWFwzhB72SeuRmXhIWEiQNhw6ZqLgqorXsx4uWqiA6KVQAqW+NYfZEmEWLASB/9Yv1ZIaLnF3fj+hoGSSdiSLPoUHANkEe1gKM6Sq7Yi7LYtAl7InrPALdT2IKj04M5KHB6TgpxK+fh4ouwOPdWW5gQKsYhmXSx+TP2Znu8kifsjTLGTernZLkrF7+ZZxhhzn9JDdAa8sATIgCzWEy4fRkagHV4YdlOwAxu1iCTt9m8ppEDK4YGaZ07akQW7CfG2bvlJo+WfmTBhl8="
